version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI=public.ecr.aws/a5k7m5i8/simple-angular:latest
  build:
    commands:
      - docker build --tag   public.ecr.aws/a5k7m5i8/simple-angular:latest .
  post_build:
    commands:
      - docker push  public.ecr.aws/a5k7m5i8/simple-angular:latest
      - printf '[{"name":"angular","imageUri":"public.ecr.aws/a5k7m5i8/simple-angular:latest"}]' public.ecr.aws/a5k7m5i8/simple-angular:latest > imagedefinations.json
artifacts:
  files: imagedefinations.json
