version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 404973048572.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=404973048572.dkr.ecr.us-east-1.amazonaws.com/simple-angular
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simple-angular:latest .
      - docker tag simple-angular:latest 404973048572.dkr.ecr.us-east-1.amazonaws.com/simple-angular:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 404973048572.dkr.ecr.us-east-1.amazonaws.com/simple-angular:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' angular $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
